name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: taiki-e/install-action@nextest
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo llvm-cov nextest  --lcov --output-path lcov.info --no-fail-fast
    - name: Upload coverage data to codecov
      uses: codecov/codecov-action@v3
      with:
        files: lcov.info
        token: ${{ secrets.COV_TOKEN }}